# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_userprofile_manager_and_details'),
        ('delivery', '0008_projectscopeaddition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[
                    ('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('wfh_swap', 'WFH Day Swap'),
                    ('wfh_standing', 'Standing WFH Day Change'), ('other', 'Other'),
                ], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, help_text="The purpose of the request. Required for 'Other'.")),
                ('swap_original_date', models.DateField(blank=True, null=True)),
                ('standing_weekday', models.IntegerField(blank=True, choices=[
                    (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'),
                    (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'),
                ], null=True)),
                ('standing_action', models.CharField(blank=True, choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'),
                ], default='pending', max_length=10)),
                ('decline_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('notification_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WFHDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[
                    (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'),
                    (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'),
                ])),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('user', 'weekday')},
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_teams', models.ManyToManyField(blank=True, related_name='+', to='tenants.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_scope', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
