# Generated by Django 6.0.7 on 2026-08-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('wfh_swap', 'Standing WFH Day Swap'), ('wfh_standing', 'Request permanent WFH day change'), ('other', 'Other')], max_length=20),
        ),
    ]
