# Generated by Django 6.0.7 on 2026-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_project_billing_organisation_projectstakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstakeholder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
