# Generated by Django 6.0.7 on 2026-08-05 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_project_activated_at'),
        ('tenants', '0007_modality_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScopeAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_original_scope', models.BooleanField(default=True)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.modality')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_additions', to='delivery.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['is_original_scope', 'suffix'],
                'unique_together': {('project', 'modality')},
            },
        ),
    ]
