# Generated by Django 6.0.7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0008_projectscopeaddition"),
        ("tenants", "0012_leave_approval_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="modalities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Disciplines contributing to this deadline. If blank, the project's modalities are used for calendar scope display.",
                related_name="milestones",
                to="tenants.modality",
            ),
        ),
    ]
