# Generated by Django 6.0.7 on 2026-08-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_projectscopeaddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('accounts', 'Accounts'), ('client_follow_up', 'Client follow-up'), ('proposal', 'Proposal'), ('project_delivery', 'Project delivery'), ('authority', 'Authority'), ('compliance', 'Compliance'), ('internal', 'Internal'), ('personal', 'Personal'), ('site_visit', 'Site visit')], max_length=30),
        ),
    ]
