# Generated by Django 6.0.7 on 2026-08-11 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_task_category'),
        ('tenants', '0013_deadlinecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='category',
            field=models.ForeignKey(blank=True, help_text='What kind of deadline/meeting this is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='tenants.deadlinecategory'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='deadline_time',
            field=models.TimeField(blank=True, help_text='Optional - if set, people involved get an in-app popup reminder around this time on the day.', null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What % of the project's total fee this stage represents, for the payment schedule. Only relevant when 'Invoice required' is ticked.", max_digits=5, null=True),
        ),
    ]
