# Generated by Django 6.0.7 on 2026-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_modality_checklistitemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('company_admin', 'Company Administrator'), ('director', 'Director'), ('project_manager', 'Project Manager'), ('engineer', 'Engineer'), ('administration', 'Administration'), ('accounts', 'Accounts'), ('external_consultant', 'External Consultant'), ('client_user', 'Client User'), ('read_only', 'Read Only')], max_length=30),
        ),
    ]
