# Generated by Django 6.0.7 on 2026-08-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_team_modalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='code',
            field=models.CharField(blank=True, help_text="Short suffix used when this discipline is added to a project after it's already created, e.g. 'E' for Electrical -> PJ-2024-001-E.", max_length=5),
        ),
    ]
