# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_modality_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_tenant_admin',
            field=models.BooleanField(default=False, help_text="Can manage this tenant's Users, Teams and Modalities from the Manage area, without needing Django's backend admin. Separate from their day-to-day role above - e.g. an Administration user can be a Tenant Admin without being a Director."),
        ),
    ]
