# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_proposal_access_and_dashboard_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='direct_reports', to=settings.AUTH_USER_MODEL,
                help_text="This person's line manager - who approves their leave and WFH requests, "
                          "in addition to any Director or Company Administrator.",
            ),
        ),
    ]
