# Generated by Django 6.0.7 on 2026-08-08 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_proposal_access_and_dashboard_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # is_tenant_admin's actual column was already dropped from the
        # production DB by 0008_drop_stray_is_tenant_admin (raw SQL,
        # IF EXISTS) - only Django's migration *state* still thinks the
        # field exists. A plain RemoveField here would try to
        # "ALTER TABLE ... DROP COLUMN is_tenant_admin" again and fail
        # with "column does not exist" on production. Splitting state
        # from database keeps the state in sync without touching the
        # already-correct database schema.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userprofile',
                    name='is_tenant_admin',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_started',
            field=models.DateField(blank=True, help_text='Date they started with the company.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direct_manager',
            field=models.ForeignKey(blank=True, help_text='Leave requests from this person are routed to their direct manager for approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modalities',
            field=models.ManyToManyField(blank=True, help_text="Disciplines this person personally works in - independent of their team's modalities.", related_name='user_profiles', to='tenants.modality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
