# Generated by Django 6.0.7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_remove_userprofile_is_tenant_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="The manager responsible for this team in the Calendar and Management Hub.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
