# Generated by Django 6.0.7 on 2026-08-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_remove_userprofile_is_tenant_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # A clean rename (not remove+add) so anyone who already has a
        # direct_manager set on production keeps that assignment -
        # this field was live on production before the Calendar module
        # renamed it to match the leave app's naming.
        migrations.RenameField(
            model_name='userprofile',
            old_name='direct_manager',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text="This person's line manager - who approves their leave and WFH requests, in addition to any Director or Company Administrator.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
