# Generated by Django 6.0.7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tenants", "0011_team_manager")]

    operations = [
        migrations.AddField(model_name="tenant", name="leave_approval_reminder_days", field=models.PositiveIntegerField(default=2, help_text="Business days before a pending leave/WFH approval reminder is raised.")),
        migrations.AddField(model_name="tenant", name="leave_approval_escalation_days", field=models.PositiveIntegerField(default=3, help_text="Business days before a pending leave/WFH approval is escalated to Company Admin.")),
    ]
