# Generated by Django 6.0.7 on 2026-08-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_userprofile_manager_and_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='calendar_name_display',
            field=models.CharField(choices=[('auto', 'First name only - add last initial automatically if two people share a first name'), ('first_name', "First name only, always (even if it's ambiguous)"), ('first_last_initial', 'First name + last initial, always')], default='auto', help_text="How people's names are shown on the Calendar and dashboard 'who's out today' widgets.", max_length=20),
        ),
    ]
