# Generated by Django 6.0.7 on 2026-08-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_calendar_name_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_categories', to='tenants.tenant')),
            ],
        ),
    ]
