# Generated by Django 6.0.7 on 2026-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_deadlinecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinecategory',
            name='color',
            field=models.CharField(default='#dc2626', help_text="Hex colour used to badge this category's deadlines on the Calendar (e.g. #dc2626).", max_length=7),
        ),
    ]
