# Auto-generated by an extraction pass over the Elev8 Fee Proposal template.
# Content is REAL, taken directly from the template document - not placeholder text.
from django.core.management.base import BaseCommand

from tenants.models import Tenant, Modality
from crm.models import FPScopeItem, FPExclusionItem, FPTermClause, FPPaymentTermOption


MODALITIES = [
    ("Electrical", "E"),
    ("ESD", "ESD"),
    ("Fire", "F"),
    ("Hydraulic", "H"),
    ("Mechanical", "M"),
    ("NBNco Pathway", "NBN"),
    ("Stormwater", "SW"),
    ("Vertical Transportation", "VT"),
]

SCOPE_ITEMS = {
    None: [
        """Attendance at ____ project design meetings (additional meetings will be charged at hourly rates)""",
        """Attendance at ____ Zoom/Online project design meetings (additional meetings will be charged at hourly rates)""",
        """Attendance at site to survey existing services/installation (1 visit allowed)""",
        """Being provided with existing services documentation (if available)""",
        """Based on ceiling being exposed soffit throughout""",
        """Constant design and documentation phase from commencement of project""",
        """Services Spatials Will be provided for incorporation into Architectural Package""",
        """Elev8 will not be held responsible for not meeting deadlines due to other Parties not providing information and allowing adequate time to produce Documentation""",
        """Elev8 will not be held responsible for not meeting deadlines due to other Authority time frames and delayed responses""",
        """Fee is based on X set of updated Architectural drawings through the design and documentation phase which require Elev8 Consulting Services Pty Ltd to update drawing backgrounds accordingly.""",
        """R126 Certification""",
    ],
    "Electrical": [
        """Liaison with all relevant Authorities""",
        """Maximum Demand Calculation""",
        """Negotiations with the Supply Authority for a suitable electricity supply""",
        """Locating on site kiosk, indoor substation or pole mounted transformer""",
        """Locating supply termination pillar at boundary""",
        """Site main switchboard and supply disconnection facility""",
        """Metering arrangement""",
        """Power Main design and documentation""",
        """Power sub main design and documentation""",
        """Distribution boards""",
        """Power reticulation to outlets and equipment""",
        """Body protection to electrical circuits where required""",
        """Internal Lighting""",
        """External building Lighting""",
        """External carpark and pathway Lighting""",
        """External court Lighting""",
        """Lighting control system""",
        """Lighting control system to common areas only""",
        """Emergency and exit lighting""",
        """Nbnco services provisions (excludes pathway designs)""",
        """Internal communications cabling and WIFI""",
        """Data cabling from rack to outlets""",
        """Fibre links between buildings""",
        """HDMI and Data cabling/outlets""",
        """Projector connections""",
        """Speakers""",
        """WAP connectivity""",
        """Cabling to Interactive Projectors""",
        """PA system with internal and external speaker""",
        """Hearing Augmentation System""",
        """Smoke/thermal alarm systems to AS 1670 to all common and public areas""",
        """Smoke/thermal alarm systems to AS 1670""",
        """Local hard wired c/w battery backup residential smoke detection""",
        """Fire indicator panel""",
        """Fire indicator panel upgrade and alterations""",
        """Occupant warning system""",
        """M.A.T.V. and Pay-Tv""",
        """Electric heater panels""",
        """Telephone system""",
        """Nurse Call system""",
        """Security systems, Access control and CCTV""",
        """Power supplies to mechanical services equipment""",
        """Power supplies to mechanical services switchboards""",
        """Power supplies to hydraulic services equipment""",
        """Section J compliance to design""",
        """Works as outlined within the fire safety engineering brief.""",
        """Preparation of drawings for tender to suitable contractors""",
        """Preparation of specifications for tender to suitable contractor""",
    ],
    "ESD": [
        """Assessment prepared in conjunction with NCC relevant to the project""",
        """Deemed to Satisfy NCC Part J1 to J8 assessment""",
        """Preparation of NCC Section J Report""",
        """First Rate 5 Assessment and report""",
        """Preliminary and Final Reports provided""",
    ],
    "Fire": [
        """Existing Fire sprinklers system in accordance with AS2118.1 Alterations and Additions""",
        """Existing Fire hydrants and hosereels Alterations and Additions""",
        """Water supplies for the sprinkler system""",
        """Water supplies for the Fire Services""",
        """Fire sprinkler control valve set""",
        """Fire sprinkler booster set""",
        """Fire sprinklers system in accordance with AS2118.1 to basement level only""",
        """Fire sprinklers system in accordance with AS2118.1""",
        """Fire sprinklers system to car stackers in accordance with AS2118.1 and FRV GL32""",
        """Fire sprinklers system in accordance with AS2118.4""",
        """Fire sprinkler pump set and static storage tanks""",
        """Fire hydrants, Hydrant Booster set and Fire hose reels""",
        """Fire hydrant pump set and static storage tanks""",
        """Obtaining water mains pressure and flow for fire Services (application or testing costs excluded)""",
        """Works as outlined within the fire safety engineering brief.""",
        """Preparation of drawings for tender to suitable contractors""",
        """Preparation of specifications for tender to suitable contractors""",
    ],
    "Hydraulic": [
        """Liaison with all relevant Authorities""",
        """Incoming water supply for domestic and fire services""",
        """Main water meter assembly""",
        """Hot and cold water internally""",
        """Hot water plant""",
        """Individual authority cold water check meters""",
        """Individual hot water check meters""",
        """Recycled Water pressure pump to serve wc's and irrigation""",
        """Sewer drainage and sanitary plumbing""",
        """Sewer tapping arrangement""",
        """Locate and connect into existing Sewer tapping arrangement""",
        """Sewerage treatment plant in accordance with local Council requirements""",
        """Gas reticulation from Common authority meter to appliances/equipment""",
        """Gas reticulation from authority meter to equipment/appliances""",
        """Trade waste reticulation to Retail via grease interceptor trap""",
        """Trade waste reticulation to kitchen via grease interceptor trap""",
        """Trade waste reticulation to canteen via grease interceptor trap""",
        """Trade waste reticulation to Science room via neutralizer trap""",
        """Trade waste reticulation to Art room via settling trap""",
        """Roof Gutter and sump design and documentation""",
        """Downpipe design and documentation\\ (note drainage termination at Ground level -- continuation by Civil Engineer)""",
        """Pool plant waste, water and gas supply""",
        """Fire hydrants, Hydrant Booster set and Fire hosereels""",
        """Fire hydrants and Fire hose reels""",
        """Fire hydrant pump set and static storage tanks""",
        """Fire sprinkler water supply""",
        """Obtaining water mains pressure and flow for fire Services (application or testing costs excluded)""",
        """Works as outlined within the fire safety engineering brief.""",
        """Preparation of drawings for tender to suitable contractors""",
        """Preparation of specifications for tender to suitable contractors""",
    ],
    "Mechanical": [
        """Wall mounted split Air conditioning to living area of each apartment""",
        """Under ceiling split Air conditioning""",
        """Ceiling cassette split Air conditioning""",
        """Bulkhead type split reverse cycle air conditioning to each apartment""",
        """Ducted split reverse cycle air conditioning to each apartment""",
        """Ducted split reverse cycle air conditioning to each tenancy""",
        """Multi head, Wall mounted split air conditioning to each apartment""",
        """Multi Head, Bulkhead type split reverse cycle air conditioning to each apartment""",
        """Central fan coil unit and air cooled condensing unit""",
        """Cold isle air return and heat reclaim""",
        """Gas fired console heaters""",
        """Gas fired ducted heating systems""",
        """Hydronic and or slab heating""",
        """Radiant heaters""",
        """Evaporative cooling""",
        """Dust extraction""",
        """Welding extraction""",
        """Compressed air system""",
        """Fume cupboards""",
        """Existing Ducted air conditioning Alterations and Additions (Note: existing supply and return air grille readings to be tested and advised by Landlord prior to design)""",
        """Additional air conditioning as required.""",
        """Mechanical ventilation system in accordance with AS 1668.2, upgrade as required to suit people numbers (Note: existing ventilation rates to be tested and advised by Landlord prior to design)""",
        """Mechanical ventilation system in accordance with AS 1668.2 to basement carpark""",
        """Mechanical ventilation system in accordance with AS 1668.2 to Lockers""",
        """Mechanical ventilation system in accordance with AS 1668.2 to Change Room""",
        """Mechanical ventilation system in accordance with AS 1668.2 to amenities""",
        """Mechanical ventilation system in accordance with AS 1668.2 to cleaners room""",
        """Mechanical ventilation system in accordance with AS 1668.2 to bin room""",
        """Mechanical ventilation system in accordance with AS 1668.2 to bathroom, powder room and ensuites""",
        """Mechanical ventilation system in accordance with AS 1668.2 to Apartments""",
        """Mechanical ventilation system in accordance with AS 1668.2 to Domestic Rangehoods""",
        """Mechanical ventilation system in accordance with AS 1668.2 to Laundry""",
        """Mechanical ventilation system in accordance with AS 1668.2 to kitchen""",
        """Mechanical fresh air ventilation system in accordance with AS 1668.2""",
        """Natural fresh air ventilation system in accordance with AS 1668.4""",
        """Section J compliance to design""",
        """Works as outlined within the fire safety engineering brief.""",
        """Preparation of drawings for tender to suitable contractors""",
        """Preparation of specifications for tender to suitable contractors""",
    ],
    "NBNco Pathway": [
        """Liaising with NBNCo to project number and application""",
        """Negotiations with NBNCo for communications lead in location (site specific)""",
        """Internal site conduits, cabling and termination points""",
        """Documentation in accordance with NBNCo Guidelines""",
        """Preparation of drawings for approval by NBNCO tender to suitable contractors""",
        """Preparation of drawings for tender to suitable contractors""",
    ],
    "Stormwater": [
        """Liaison with all relevant Authorities""",
        """Roof Gutter and sump design and documentation""",
        """Downpipe design and documentation (note drainage termination at high level of basement -- continuation by Civil Engineer)""",
        """Balcony design and documentation (note drainage termination at high level of basement -- continuation by Civil Engineer)""",
        """Rainwater storage tank design""",
        """Basement carpark drainage""",
        """Drainage to legal point of discharge as advised by the local council""",
        """Preparation of drawings for tender to suitable contractors""",
        """Preparation of specifications for tender to suitable contractors""",
    ],
    "Vertical Transportation": [
        """Determining Lift shaft, overrun and pit sizes""",
        """Obtaining quotation of Lifts to suit the specific building requirements""",
        """Preparation of specification for tender to suitable contractors""",
    ],
}

EXCLUSION_GROUPS = [
    (None, False, False, False, [
        """Revit documentation (CAD format provided)""",
        """Site survey and inspection""",
        """Project meetings""",
        """Underground services location""",
        """Staged works documentation""",
        """Works to existing areas outside specified scope""",
        """Services specifications. Details on drawings provided""",
        """Preparation of Reflected ceiling plans""",
        """Preparing budgets""",
        """Preparing Hydraulic Services budgets""",
        """Preparing Electrical Services budgets""",
        """Preparing Mechanical Services budgets""",
        """Demolition works and associated documentation""",
        """Decanting Documentation""",
        """Base Building Consulting Engineer Peer Review comments and updates to documents""",
        """Employment of the Base Building Consulting Engineer Peer Review for any approvals""",
        """ESD""",
        """Electrical Services""",
        """Fire Services""",
        """Fire Sprinklers""",
        """Hydraulic Services""",
        """Mechanical Services""",
        """R126 Certification""",
        """R126 Certification - on single residential projects""",
    ]),
    ("Electrical", False, False, False, [
        """Mains cable size to each floor to be advised by Landlord""",
        """Amps available to each floor to be advised by Landlord""",
        """Adequate communication infrastructure available""",
        """Load Testing of existing services. Eg Power supply""",
        """Security systems including access control""",
        """Stage Lighting systems and lighting bars for Performing arts""",
        """Lighting layouts by Architect""",
        """Power and Data layouts by Architect""",
        """Lighting control systems throughout""",
        """Lighting control systems to apartments""",
        """Alternate lighting manufacturer review and section J compliance updates""",
        """C Bus control systems or equivalent""",
        """Audio systems and associated wiring inc. music and surround sound systems""",
        """Public address systems""",
        """Data racks and associated switches/equipment""",
        """Telephone systems""",
        """UPS (uninterrupted power supply)""",
        """Standby Generators""",
        """Body protection to electrical circuits""",
        """Smoke/thermal alarm systems to AS 1670 to all common and public areas""",
        """Smoke/thermal alarm systems to AS 1670""",
        """Local hard wired c/w battery backup residential smoke detection""",
        """Fire indicator panel""",
        """Fire indicator panel upgrade and alterations""",
        """Communications equipment for gaming machines""",
        """Data cabling fit off to gaming machines""",
        """TAB equipment and cabling""",
    ]),
    ("ESD", False, False, False, [
        """Employment of an Energy Consultant""",
        """NCC Section J1-J4 and J8 assessment ```{=html} <!-- --> ```""",
        """JV3 Assessment and modelling""",
        """First Rate 5 Assessment and report""",
    ]),
    ("Fire", False, False, False, [
        """Testing of existing services. Eg. Fire hydrants""",
        """Fire Extinguishers""",
        """Fire sprinklers to residential levels""",
        """Fire sprinklers to office levels""",
        """Fire sprinklers to basement""",
        """Fire sprinklers throughout (additional fees applicable of $*.00+GST is required)""",
        """Fire hydrants and hose reels""",
        """Upgrade of existing site fire services to meet current regulations""",
        """Design of static storage tanks and or pump systems for fire services""",
        """Submitting an application to relevant Fire Authority to obtain consent for non-compliances.""",
        """Submitting an application for a Pre Application FRV R129 to relevant Fire Authority to obtain preliminary consent (if required a fee of $2,000+GST is applicable, excluding FRV Assessment charges)""",
        """Submitting an application for a formal Regulation FRV R129 to relevant Fire Authority to obtain consent (if required a fee of $2,500+GST is applicable, excluding FRV Assessment charges)""",
        """Costs associated with Obtaining water main pressure and flow data tests.""",
        """Field/site Testing of existing services. Eg. Fire hydrants [Note: All costs above exclude authority charges applicable to all applications which will be therefore invoiced accordingly when received by our office.]{.underline}""",
    ]),
    ("Hydraulic", False, False, False, [
        """Gas Reticulation""",
        """Land capability assessments (LCA)""",
        """Septic or waste treatment plant""",
        """Grey water plant""",
        """Black water plant""",
        """Trade waste apparatus and reticulation""",
        """Build over easements applications to relevant authority (if required a fee of $500+GST is applicable)""",
        """Application for sewer and water PIC (if required a fee of $750+GST is applicable)""",
        """Application for Inline Pump for the Fire Services (if required a fee of $500+GST is applicable)""",
        """Application for sewer and water -- Form 1 QLD (if required a fee of $750+GST is applicable)""",
        """Application for sewer and water -- Section 68 NSW (if required a fee of $750+GST is applicable)""",
        """Application for Gas supply and metering (if required a fee of $750+GST is applicable)""",
        """Application for trade waste apparatus""",
        """Stormwater roof Gutter, sump, downpipe and balcony drainage""",
        """Stormwater civil design and documentation""",
        """Stormwater rainwater storage tank design""",
        """Stormwater performance assessment for charged downpipe system if required""",
        """Fire hydrants and hose reels""",
        """Upgrade of existing site fire services to meet current regulations""",
        """Design of static storage tanks and or pump systems for fire services""",
        """Submitting an application to relevant Fire Authority to obtain consent for non-compliances.""",
        """Submitting an application for a Pre Application FRV R129 to relevant Fire Authority to obtain preliminary consent (if required a fee of $2,000+GST is applicable, excluding FRV Assessment charges)""",
        """Submitting an application for a formal Regulation FRV R129 to relevant Fire Authority to obtain consent (if required a fee of $2,500+GST is applicable, excluding FRV Assessment charges)""",
        """Costs associated with Obtaining water main pressure and flow data tests.""",
        """Field/site Testing of existing services. Eg. Fire hydrants [Note: All costs above exclude authority charges applicable to all applications which will be therefore invoiced accordingly when received by our office.]{.underline}""",
    ]),
    ("Mechanical", False, False, False, [
        """Stair pressurisation -- building under 25m""",
        """Computational Fluid Dynamic calculations (carpark ventilation)""",
        """Computational Fluid Dynamic calculations -- independent certification""",
        """Carpark ventilation system""",
        """Smoke extraction""",
        """Fully ducted split Air Conditioning""",
        """Air Conditioning""",
        """Hydronic Heating""",
        """Evaporative cooling""",
        """Kitchen and dishwasher exhaust canopies and associated exhaust systems""",
        """Compressed air""",
        """Welding extraction""",
        """Dust extraction systems""",
        """Fuel tank and reticulation systems""",
        """Medical gases""",
        """Supply and return air grille readings to be tested and advised by Landlord""",
        """Ventilation rates to be tested and advised by Landlord""",
    ]),
    ("NBNco Pathway", False, False, False, [
        """NBNCo Pathway design and documentation (additional fees applicable of $*.00+GST is required)""",
    ]),
    (None, True, False, False, [
        """Vertical Transportation - design, selection and specification""",
        """Building management system""",
        """Retail Tenancy fit out works""",
        """Office Tenancy fit out works""",
        """Purchaser requirements/additions""",
        """Fire safety engineering Consulting""",
        """Passive Fire Protection Consulting""",
        """NCC S43C9 requirements due to BAL rating""",
        """Acoustic report""",
        """The design of any service negotiations with the Authorities in the event that any service is not available at the site boundary""",
        """All fees and charges levied by the Authority. As required, these will be added on as reimbursement costs""",
        """All work related to obtaining dispensations to the Building Code""",
        """Performance Solutions -- additional fees will apply where required""",
        """Section 74b, NSW -- additional fees will apply where required""",
        """CFSP Certification, NSW -- additional fees will apply where required""",
        """Safety in Design Certification""",
        """Responding to a preferred Builder during design and documentation phase unless agreed prior.""",
        """Amending documentation to suit Builder value management items during design and documentation phase""",
        """Document upload and download from Procore, Aconex or similar during design and documentation phase""",
    ]),
    (None, False, True, False, [
        """Amending documentation to suit Builder value management items.""",
        """Document upload and download from project management programs Procore, Aconex or similar (additional 25% Contract Administration Stage fee applies if required)""",
        """Reviewing alternate equipment ie. Lighting Specifications will be at hourly rates.""",
        """Preparation of shop drawings or As Built drawings""",
    ]),
    (None, False, False, True, [
        """Remaining (where applicable) Design and documentation fees to suit builder's scope""",
        """Fixed construction fees to suit builder's scope""",
        """Reviewing alternate equipment ie. Lighting Specifications will be at hourly rates.""",
    ]),
]

TERM_CLAUSES = [
    (1, """The above fees have been assessed on the scope of the project as outlined above and upon the information prepared by your office, dated XX.XX.2026."""),
    (2, """Fees are based on the project budget of $0,000,000.00. Where the project budget increases Elev8 Consulting Services Pty Ltd reserve the right to request fees to be renegotiated and scaled proportionally to the increase of the project budget."""),
    (3, """These fees area based upon disciplines as quoted being accepted. Elev8 Consulting Services Pty Ltd reserve the right to amend individual discipline fees if not all services are approved to cover documentation set up, administration, inspection and meeting costs allocated to the initial fee as applicable."""),
    (4, """Any amendments or changes to the planning of the project which necessitate major re-design or re-drafting of completed work will be additional to the above fees. Separate times shall be kept of this additional work and will be charged for an hourly-rate basis. Approval shall be provided prior to commencement of any works"""),
    (5, """Director/Senior Engineer = $250/hr + GST | Draftsperson = $160/hr + GST | Administration = $120/hr + GST"""),
    (6, """Fees are valid for sixty (60) days from submission date. Construction rates are valid for twelve (12) months from commencement of project design. Fees after this time will be adjusted accordingly to suit increases."""),
    (7, """Design fees are based upon project development being constant. If the project from commencement of design is placed on hold for in excess of 3 months Elev8 Consulting Services Pty Ltd reserve the right to review fees and works necessary to recommence design and documentation."""),
    (8, """The fees are invoiced progressively. Failure to pay invoice by the due date will incur Elev8 to cease all works and document distribution until payment is made in full."""),
    (9, """INVOICE AND PAYMENT TERMS"""),
    (10, """Elev8 Consulting Services Pty Ltd reserve the right to request payment prior to documentation issue."""),
    (11, """All accounts are due for payment within 3 days. Any amounts beyond 3 days will be charged interest at the bank rate plus 2% and works will cease on project until payment is made in full."""),
    (12, """Elev8 Consulting Services Pty Ltd reserve the right to take necessary action to recover all outstanding overdue accounts which may affect Credit Rating. Elev8 Consulting Services Pty Ltd reserve the right to forward all collection and legal costs on accordingly."""),
    (13, """All invoice discrepancies that are found shall be advised within 2 days of receipt of the invoice to enable re-issue."""),
    (14, """Invoices shall be reviewed and approved then forwarded to the relevant client within 2 days of receipt."""),
    (15, """Elev8 Consulting Services Pty Ltd reserve the right to issue Invoices for full payment prior to release of documents."""),
    (16, """Payment arrangements are not accepted. Fee payments are not subject to client bank finance or draw down facilities being processed. Failure to make payment by the specified date will occur interest and documentation will be held and revoked at any time."""),
    (17, """If project is placed on 'hold' or 'works ceased' all completed documentation/meetings/authority negotiations will be invoiced to the date and time our office is formally advised in writing to 'Hold' or 'cease works' on project, this instruction must be from the person and or company who accepted fees accordingly. Elev8 Consulting Services Pty Ltd deserves the right to invoice for all works completed up and until this time."""),
    (18, """All payment claims are under the Building and Construction Industry Security of Payment act."""),
    (19, """Elev8 Consulting Services Pty Ltd Holds Professional indemnity insurance to the value of $10,000,000 and public liability insurance of $20,000,000. Copies of the relevant policies will be provided upon request."""),
    (20, """The fees exclude the costs to print/plot drawings. The supply of documents will be at a cost of $3.00 for A1 size, $4.00 for B1 size and $5.00 for A0 size."""),
    (21, """Elev8 Consulting Services Pty Ltd will distribute CAD format documentation for the records of the architect and/or client only. These are not for purposes of contractors to prepare shop drawings. Elev8 Consulting Services Pty Ltd reserves the right to charge any Contractor or Subcontractor $200.00+gst per drawing if requested for shop drawing purposes."""),
    (22, """Preliminary documentation is not to be used for any form of Building Permit or Tender/quotations unless approved by Elev8 Consulting Services Pty Ltd."""),
    (23, """Elev8 Consulting Services Pty Ltd will not be liable for ensuring all planning permit conditions are met. It is the Clients and or architects responsibility to cross check all documents and apply for amendments as required to the planning permit."""),
    (24, """Sufficient time allocation for completion of documentation to be provided upon receipt of completed Architectural and Structural documentation. Min. 5 Business days unless negotiated otherwise with our office."""),
    (25, """Elev8 Consulting Services Pty Ltd will not be held responsible for inability of meeting deadlines due to other parties and insufficient time allocation to produce or complete documentation."""),
    (26, """Elev8 Consulting Services Pty Ltd will not be responsible for authority timeframes or requirements."""),
    (27, """Elev8 Consulting Services Pty Ltd will not be responsible for authority guidelines or offer requirements which in turn may affect the project. Agreeing to the conditions removes Elev8 Consulting Services Pty Ltd of being held responsible."""),
    (28, """Elev8 Consulting Services Pty Ltd will not be responsible for authority adjusting water supply, pressure and/or flows to the subject site at any time which in turn may affect the project and design criteria. Agreeing to the conditions removes Elev8 Consulting Services Pty Ltd of being held responsible."""),
    (29, """Elev8 Consulting Services Pty Ltd will invoice any authority costs/changes, application fees or independent contractor costs where applicable including the FRV application fees by our office."""),
    (30, """Elev8 Consulting Services Pty Ltd will invoice for any re applications to authorities if offers have lapsed due to non-acceptance and non-payment by client or other parties at a rate or $250/hr +GST (min. charge $750 +GST)."""),
    (31, """This fee agreement or alternatively a AS4000 Contract must be completed and returned prior to commencement. Alternate contracts or specifically Novation Agreements will require a third-party independent review and approval prior to signing Elev8 Consulting Services Pty Ltd reserve the right to forward all third party/legal costs for payment prior."""),
]

PAYMENT_TERMS = [
    ("""25% Deposit shall be paid prior to commencement of any works relating to the project""", 25),
    ("""25% payment is required upon Site Survey completion.""", 25),
    ("""25% payment is required at Services spatial and/or typical layout documentation""", 25),
    ("""50% payment is required at initial preliminary documentation""", 50),
    ("""20% payment is required at final preliminary documentation""", 20),
    ("""5% payment is required at tender, construction and or building permit issue""", 5),
]

class Command(BaseCommand):
    """
    One-time seed of the Fee Proposal content library (scope items,
    exclusions, T&C clauses, payment terms) from Elev8's real Fee
    Proposal template. Safe to run more than once - it checks
    whether the library already exists for the tenant and does
    nothing if so, so it won't duplicate rows or clobber any manual
    corrections made via Admin after the first run.
    """

    help = "Seed the Fee Proposal content library from the Elev8 template (idempotent)"

    def handle(self, *args, **options):
        tenant = Tenant.objects.filter(is_active=True).first()
        if not tenant:
            self.stdout.write(self.style.ERROR("No active tenant found - nothing to seed."))
            return

        if FPTermClause.objects.filter(tenant=tenant).exists():
            self.stdout.write("Fee Proposal content library already seeded for this tenant - skipping. "
                               "Edit existing content via Admin instead of re-running this.")
            return

        # --- Modalities (get-or-create, so this plays nicely if some already exist) ---
        modality_objs = {}
        for name, code in MODALITIES:
            obj, _ = Modality.objects.get_or_create(tenant=tenant, name=name, defaults={"code": code})
            modality_objs[name] = obj

        # --- Scope items ---
        scope_count = 0
        for modality_name, items in SCOPE_ITEMS.items():
            modality = modality_objs.get(modality_name) if modality_name else None
            for i, text in enumerate(items):
                FPScopeItem.objects.create(tenant=tenant, modality=modality, text=text, order=i)
                scope_count += 1

        # --- Exclusion items ---
        exclusion_count = 0
        for modality_name, is_misc, is_ca, is_nov, items in EXCLUSION_GROUPS:
            modality = modality_objs.get(modality_name) if modality_name else None
            for i, text in enumerate(items):
                FPExclusionItem.objects.create(
                    tenant=tenant, modality=modality, is_miscellaneous=is_misc,
                    is_contract_administration=is_ca, is_novation=is_nov, text=text, order=i,
                )
                exclusion_count += 1

        # --- Term clauses ---
        for number, text in TERM_CLAUSES:
            FPTermClause.objects.create(tenant=tenant, number=number, text=text)

        # --- Payment term options ---
        for i, (text, pct) in enumerate(PAYMENT_TERMS):
            FPPaymentTermOption.objects.create(tenant=tenant, text=text, default_percentage=pct, order=i)

        self.stdout.write(self.style.SUCCESS(
            f"Seeded {len(modality_objs)} modalities, {scope_count} scope items, "
            f"{exclusion_count} exclusion items, {len(TERM_CLAUSES)} T&C clauses, "
            f"{len(PAYMENT_TERMS)} payment term options."
        ))
        self.stdout.write(self.style.WARNING(
            "Review the T&C clauses in Admin and mark the ones that should be mandatory - "
            "all 31 currently default to optional/selectable."
        ))
