# Generated by Django 6.0.7
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0012_leave_approval_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=100)),
                ("colour", models.CharField(default="#2563eb", max_length=20)),
                ("text_colour", models.CharField(default="#ffffff", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["order", "name"],
                "constraints": [models.UniqueConstraint(fields=("tenant", "code"), name="uniq_calendar_event_type_tenant_code")],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=100)),
                ("colour", models.CharField(default="#7c3aed", max_length=20)),
                ("counts_toward_leave", models.BooleanField(default=True)),
                ("requires_reason", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["order", "name"],
                "constraints": [models.UniqueConstraint(fields=("tenant", "code"), name="uniq_leave_type_tenant_code")],
            },
        ),
        migrations.CreateModel(
            name="CalendarPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("show_leave", models.BooleanField(default=True)),
                ("show_wfh", models.BooleanField(default=True)),
                ("show_deadlines", models.BooleanField(default=True)),
                ("show_tasks", models.BooleanField(default=True)),
                ("show_followups", models.BooleanField(default=True)),
                ("show_projects", models.BooleanField(default=True)),
                ("show_fee_proposals", models.BooleanField(default=False)),
                ("show_company_wide", models.BooleanField(default=False)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="WFHSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="wfh_schedule", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=150)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["date"],
                "constraints": [models.UniqueConstraint(fields=("tenant", "date"), name="uniq_public_holiday_tenant_date")],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_part", models.CharField(choices=[("full", "Full day"), ("am", "Morning (half day)"), ("pm", "Afternoon (half day)")], default="full", max_length=4)),
                ("end_part", models.CharField(choices=[("full", "Full day"), ("am", "Morning (half day)"), ("pm", "Afternoon (half day)")], default="full", max_length=4)),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending approval"), ("approved", "Approved"), ("declined", "Declined"), ("cancelled", "Cancelled")], default="pending", max_length=12)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("current_approver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pending_leave_approvals", to=settings.AUTH_USER_MODEL)),
                ("leave_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="calendar_app.leavetype")),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leave_requests", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [models.Index(fields=["tenant", "status", "start_date"], name="calendar_ap_tenant__8e5a32_idx"), models.Index(fields=["tenant", "current_approver", "status"], name="calendar_ap_tenant__1b5a6c_idx")],
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("approved", "Approved"), ("declined", "Declined"), ("cancelled", "Cancelled"), ("reassigned", "Reassigned")], max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("acted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leave_approval_actions", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_history", to="calendar_app.leaverequest")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={"ordering": ["-acted_at"]},
        ),
        migrations.CreateModel(
            name="WFHChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("change_type", models.CharField(choices=[("swap", "Swap WFH day"), ("add", "Additional WFH day"), ("remove", "Remove WFH day")], default="swap", max_length=10)),
                ("original_date", models.DateField(blank=True, null=True)),
                ("requested_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending approval"), ("approved", "Approved"), ("declined", "Declined"), ("cancelled", "Cancelled")], default="pending", max_length=12)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("current_approver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pending_wfh_approvals", to=settings.AUTH_USER_MODEL)),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wfh_change_requests", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={"ordering": ["-submitted_at"], "indexes": [models.Index(fields=["tenant", "status", "requested_date"], name="calendar_ap_tenant__9a3a6e_idx")]},
        ),
    ]
