# Generated by Django 6.0.7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("calendar_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CalendarSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reminder_after_business_days", models.PositiveIntegerField(default=2)),
                ("escalation_after_business_days", models.PositiveIntegerField(default=3)),
                ("allow_company_admin_override", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("tenant",), name="uniq_calendar_settings_tenant")],
            },
        ),
    ]
