# Generated by Django 6.0.7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("calendar_app", "0002_calendarsettings")]
    operations = [
        migrations.AddField(model_name="wfhchangerequest", name="last_reminder_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="wfhchangerequest", name="escalated_at", field=models.DateTimeField(blank=True, null=True)),
    ]
