# Generated by Django 6.0.7 on 2026-08-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalities', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('always_included', models.BooleanField(default=True, help_text="If checked, this item is added automatically whenever its modality is selected (or to every project, if no modality is set). If unchecked, it's available to add manually.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='tenants.tenant')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='tenants.modality')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
    ]
