# Generated by Django 6.0.7 on 2026-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modalities',
            field=models.ManyToManyField(blank=True, help_text='Which disciplines this team covers - used to show them their relevant active projects.', related_name='teams', to='tenants.modality'),
        ),
    ]
