# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    # Two migrations both claim '0008' and both depend on 0007 without
    # depending on each other (userprofile_is_tenant_admin added a field
    # that drop_stray_is_tenant_admin then had to remove again in prod).
    # Depending on both here merges the graph back into a single line
    # instead of leaving two dangling leaves.
    dependencies = [
        ('tenants', '0008_userprofile_is_tenant_admin'),
        ('tenants', '0008_drop_stray_is_tenant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dashboard_visibility',
            field=models.CharField(
                choices=[
                    ('restricted', "Restricted - people without Fee Proposal access see nothing "
                                    "proposal-related"),
                    ('responsible_for', "Responsible for - they also see enquiries/proposals/archived "
                                         "projects they're personally tied to, without fee amounts"),
                ],
                default='restricted',
                help_text="Controls what people WITHOUT Fee Proposal access see on their Command Centre.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_proposals',
            field=models.BooleanField(
                default=False,
                help_text="Can see and work with Fee Proposals - fee amounts, follow-ups, and (in "
                          "future) proposal letters/templates. Company Administrators and Directors "
                          "always have this regardless of this checkbox; tick it for anyone else who "
                          "should be able to create or view proposals.",
            ),
        ),
    ]
