# Generated by Django 6.0.7 on 2026-08-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_proposalfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organisation'),
        ),
    ]
