# Generated by Django 6.0.7 on 2026-07-31 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('office_phone', models.CharField(blank=True, max_length=50)),
                ('is_proposal_recipient', models.BooleanField(default=False)),
                ('is_invoice_recipient', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('organisation_type', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('client_status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive')], default='prospect', max_length=20)),
                ('vip_level', models.CharField(blank=True, max_length=50)),
                ('client_since', models.DateField(blank=True, null=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relationship_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organisations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_number', models.CharField(max_length=50, unique=True)),
                ('project_address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('services_required', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('date_received', models.DateField()),
                ('proposal_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('clarification_required', 'Clarification Required'), ('ready_to_price', 'Ready to Price'), ('proposal_required', 'Proposal Required'), ('proposal_created', 'Proposal Created'), ('declined', 'Declined'), ('closed', 'Closed')], default='new', max_length=30)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('responsible_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_enquiries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='crm.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organisation'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_number', models.CharField(max_length=50, unique=True)),
                ('scope', models.TextField(blank=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exclusions', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('validity_period_days', models.PositiveIntegerField(default=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('director_review', 'Director Review'), ('approved', 'Approved'), ('issued', 'Issued'), ('follow_up_due', 'Follow-up Due'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.enquiry')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.organisation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
