# Generated by Django 6.0.7 on 2026-07-31 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('original_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('on_hold', 'On Hold'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='setup', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('client_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.organisation')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_projects', to=settings.AUTH_USER_MODEL)),
                ('original_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.proposal')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('overdue', 'Overdue'), ('ready_for_review', 'Ready for Review'), ('ready_to_issue', 'Ready to Issue'), ('issued', 'Issued'), ('invoice_review_required', 'Invoice Review Required'), ('approved_to_invoice', 'Approved to Invoice'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('closed', 'Closed')], default='scheduled', max_length=30)),
                ('forecast_issue_date', models.DateField(blank=True, null=True)),
                ('actual_issue_date', models.DateField(blank=True, null=True)),
                ('invoice_required', models.BooleanField(default=False)),
                ('director_approval_required', models.BooleanField(default=False)),
                ('director_approval_status', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_milestones', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='delivery.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('confidentiality', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='delivery.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.milestone')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='delivery.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
