# Generated by Django 6.0.7 on 2026-08-03 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('tenants', '0003_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tenants.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('accounts', 'Accounts'), ('client_follow_up', 'Client follow-up'), ('proposal', 'Proposal'), ('project_delivery', 'Project delivery'), ('authority', 'Authority'), ('compliance', 'Compliance'), ('internal', 'Internal'), ('personal', 'Personal')], max_length=30),
        ),
    ]
