# Generated by Django 6.0.7 on 2026-08-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_proposalfollowup'),
        ('delivery', '0004_project_modalities_projectchecklistitem'),
        ('tenants', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_organisation',
            field=models.ForeignKey(blank=True, help_text='Who actually gets invoiced, if different from the client organisation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_projects', to='crm.organisation'),
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('requesting_contact', 'Requesting contact'), ('client_contact', 'Client contact'), ('billing_contact', 'Billing contact'), ('architect', 'Architect'), ('builder', 'Builder'), ('designer', 'Designer'), ('consultant', 'Consultant'), ('authority_contact', 'Authority contact'), ('site_contact', 'Site contact'), ('other', 'Other')], default='other', max_length=30)),
                ('external_name', models.CharField(blank=True, help_text='If not an existing Contact.', max_length=255)),
                ('external_company', models.CharField(blank=True, max_length=255)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('external_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stakeholder_roles', to='crm.contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='delivery.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
