# Generated by Django 6.0.7 on 2026-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_projectstakeholder_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text="Set automatically the first time this project's status becomes Active.", null=True),
        ),
    ]
